# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: mcr.microsoft.com/dotnet/sdk:latest
variables:
  OBJECTS_DIRECTORY: obj
  NUGET_PACKAGES_DIRECTORY: ".nuget"
  SOURCE_CODE_PATH: "*/*/"
cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
  - "$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json"
  - "$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*"
  - "$NUGET_PACKAGES_DIRECTORY"
  policy: pull-push
before_script:
- dotnet restore --packages $NUGET_PACKAGES_DIRECTORY
build:
  stage: build
  script:
  - dotnet build --no-restore
tests:
  stage: test
  script:
  - dotnet test --no-restore
stages:
- build
- test
- deploy
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup
sast:
  stage: test
include:
- template: Auto-DevOps.gitlab-ci.yml
